# .pre-commit-config.yaml
repos:
  # ----------------------------
  # CLANG-FORMAT (C++ Linter)
  # ----------------------------
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v17.0.6
    hooks:
      - id: clang-format
        name: clang-format
        files: \.(cpp|cc|cxx|c\+\+|h|hpp|hh|hxx)$
        args: [--style=file]  # Uses .clang-format in your repo

  # ----------------------------
  # CLANG-TIDY (Static Analyzer)
  # ----------------------------
  - repo: local
    hooks:
      - id: make-tidy
        name: make tidy
        entry: make tidy
        language: system
        pass_filenames: false

  # ----------------------------
  # GENERAL SANITY HOOKS
  # ----------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-yaml
      - id: check-executables-have-shebangs
