[File]
path = "../../sample2.mp3"

[Format]
audio_type = "mp3 (MP2/3 (MPEG audio layer 2/3))"
duration = "233"
parsed_bitrate = "131 kbps"

[Metadata]
title = "<Song-name>"
artist = "Radiohead"
track = "6/12"
album = "The Bends"
disc = "1/1"
copyright = "1995 XL Recordings Ltd"
genre = "Alternative Rock"
comment = "https://music.youtube.com/watch?v=jIjTFt6XmFM"
album_artist = "Radiohead"
TSRC = "GBAYE9400058"
encoder = "Lavf61.7.100"
encoded_by = "XL Recordings"
date = "1995"
