name: "Wavy CI / Fedora Linux Build (x86-64 arch - GCC)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - name: Update DNF and Install Dependencies
      run: |
        dnf upgrade -y
        xargs -a ci/rpm-packages.txt dnf install -y

    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Build Release Version of Wavy (x86-64 arch) - GCC
      run: |
        make init
        make
