name: "Wavy CI / Ubuntu Build with Plugins (x86-64 arch - GCC)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies for Wavy
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential libflac++-dev libboost-log-dev libboost-system-dev libboost-filesystem-dev libssl-dev \
          libavformat-dev libavutil-dev libswresample-dev libavcodec-dev \
            libzstd-dev \
            cmake make pkg-config \
            libarchive-dev \
            libmp3lame-dev libtbb-dev

    - name: Install Default Audio Backend Dependencies
      run: |
        sudo apt-get install libpulse-dev

    - name: Build Release Version of Wavy with PLUGINS (x86-64 arch) - GCC (with GNU-ld)
      run: |
        make EXTRA_CMAKE_FLAGS="-DBUILD_FETCHER_PLUGINS=ON -DBUILD_AUDIO_BACKEND_PLUGINS=ON"
