name: "Wavy CI / Ubuntu Build with Plugins (x86-64 arch - GCC)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install dependencies for Wavy
      run: |
        sudo apt-get update
        xargs -a ci/apt-packages.txt sudo apt-get install -y

    - name: Install Default Audio Backend Dependencies
      run: |
        sudo apt-get install libpulse-dev

    - name: Build Release Version of Wavy with PLUGINS (x86-64 arch) - GCC (with GNU-ld)
      run: |
        sudo make init
        make EXTRA_CMAKE_FLAGS="-DBUILD_FETCHER_PLUGINS=ON -DBUILD_AUDIO_BACKEND_PLUGINS=ON"
