name: "Wavy CI / Arch Linux Build (x86-64 arch - GCC)"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest

    steps:
    - name: Checkout repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update Pacman and Install Dependencies
      run: |
        pacman -Syu --noconfirm
        xargs -a ci/pacman-packages.txt sudo pacman -S --noconfirm

    - name: Build Release Version of Wavy (x86-64 arch) - GCC
      run: |
        make init
        make
